### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QZIHw8/pyulog/

### ISSUE THREAD

**Issue by ybtg** [PX4/pyulog#103]
When I installed pyulog under the ubuntu18.04 system on Jetson nano, the following error occurred.
My setuptools version is 44.1.1, pip version is pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7).

mavros@mavros-desktop:~$ pip install pyulog
Collecting pyulog
  Using cached https://files.pythonhosted.org/packages/c2/6c/dea17a45219681dc111590b63a14cc0b1a49773b4312546ae9938834916d/pyulog-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-QZIHw8/pyulog/setup.py", line 11, in <module>
        import versioneer
      File "versioneer.py", line 1739
        file=sys.stderr)
            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QZIHw8/pyulog/

**Comment by bkueng** [comment]
Sorry, but [python 2 isn't generally supported anymore](https://www.python.org/doc/sunset-python-2/). Please update your system.
