### ISSUE TITLE
Attitude transformation base: body / inertial frame

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/pyulog#13]
@bkueng @jgoppert We should update the routine here to allow different references:
https://github.com/PX4/pyulog/blob/b68e3a6b42a9ac6f8b577885cf343639d0641b9b/pyulog/px4.py#L76

@MaEtUgR Our flight logs show that the rate tracking is excellent but the angle tracking is off, depending on the vehicle yaw. I think there is something incorrect in the way we report roll and pitch set points currently. Example from this log:

http://logs.px4.io/plot_app?log=e55ed4c2-09db-416b-b622-98c3a18c948e

The rate tracking is excellent the angle tracking is horrible. The vehicle would have flown away given those tracking errors, so its just the reporting, not the actual flight performance which is wrong.

<img width="728" alt="screen shot 2016-12-30 at 12 47 53" src="https://cloud.githubusercontent.com/assets/1208119/21564482/621d6710-ce8e-11e6-86b4-a589d760ff57.png">

<img width="717" alt="screen shot 2016-12-30 at 12 51 57" src="https://cloud.githubusercontent.com/assets/1208119/21564513/c8ed88bc-ce8e-11e6-8cde-4faafc42a3ca.png">

If you correlate it with the yaw plot it becomes obvious that there is a missing transformation from inertial to body here. And it is interesting that the yaw angle tracking seems to be off but that's probably not what happened. This is using #6213. Is the removal of the attitude setpoint publications maybe uncovering this?

**Comment by LorenzMeier** [comment]
One of the two clearly has the wrong frame of reference and/or we're missing one transformation.

**Comment by bkueng** [comment]
I did some investigations, with the following observations so far:
- FlightPlot shows the same graphs:
![flightplot](https://cloud.githubusercontent.com/assets/281593/21607973/e37371c8-d1b9-11e6-8104-4103897f96ac.png)
- Plotting and converting from the quaternion in FlightPlot shows that `vehicle_attitude_setpoint.roll_body` and `q_d` match.
- Comparing with sdlog2: it does the same conversion from `vehicle_attitude.q` to get the roll, pitch & yaw. And for the setpoint it uses the `roll_body` which matches the quaternion data `q_d`.

Also a SITL mission does not show the problem: http://logs.px4.io/plot_app?log=7df09d3a-bc18-4fee-a9f8-d7d65cb0a9d5
I need to look closer what happens on the Firmware side.

**Comment by LorenzMeier** [comment]
Closing as stale.
