### ISSUE TITLE
CI broken after update

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/pyulog#15]
@bkueng I think this commit:
https://github.com/PX4/pyulog/commit/8301e515b873c66102d002509e614df270a37a03

Broke potentially PX4 CI. This might be because the PX4 usage is not correct, but we need to figure out how to fix it.

@AndreasAntener FYI

```
[ROSTEST]-----------------------------------------------------------------------

[px4.rosunit-box/test_mission][ERROR]-------------------------------------------
'PX4MessageDict' object has no attribute 'resample_and_concat'
 File "/usr/lib/python2.7/unittest/case.py", line 331, in run
   testMethod()
 File "/job/catkin/src/px4/integrationtests/python_src/px4_it/mavros/mission_test.py", line 372, in test_mission
   data = px4tools.ulog.read_ulog(last_log).resample_and_concat(0.1)
```

**Comment by bkueng** [comment]
Fixed in https://github.com/PX4/Firmware/pull/6339/commits/b29f8a053b68f71203103b9f21479c825c77b5c5
