### ISSUE TITLE
ulog2kml not entered as entry point in setup.py

### ISSUE THREAD

**Issue by BinSquare** [PX4/pyulog#21]
Users are not able to use ulog2kml to convert in the command line if they installed using pip. 

The cause is due to this line : 'ulog2kml=pyulog.ulog2kml:main' is missing from the setup.py file under entry_points.

**Comment by yutaoliu** [comment]
while running ulog2kml.py I had to install simplekml, but after that there is this error
` File "ulog2kml.py", line 11, in <module>
    from .core import ULog
ValueError: Attempted relative import in non-package
`

**Comment by BinSquare** [comment]
@yutailiu, how are you running it? Did you install pyulog using pip?

**Comment by BinSquare** [comment]
Fix has been merged in pull request #22
