### ISSUE TITLE
python setup.py test error

### ISSUE THREAD

**Issue by yukun2016** [PX4/pyulog#27]
![image](https://user-images.githubusercontent.com/22852074/41842136-949fc85e-789c-11e8-992d-bc1df3aa25cb.png)

**Comment by bkueng** [comment]
Hi
Can you try `pip install ddt`?

**Comment by kyuhyong** [comment]
I have similar issue when tried python setup.py test
pip install ddt solved this problem.
Looks like ddt is not contained in the install process.

**Comment by bkueng** [comment]
Fixed in https://github.com/PX4/pyulog/commit/5e51122d75a967cc08a82c7e00f17b31981b0395
