### ISSUE TITLE
 Conversion failed when I used ulog2kml

### ISSUE THREAD

**Issue by MyOnlyOnlySunshine** [PX4/pyulog#28]
Conversion failed when I used ulog2kml，but successful when i use ulog2csv

**Comment by bkueng** [comment]
What do you mean by fails? Can you provide the output? Did you install `simplekml`?

**Comment by MyOnlyOnlySunshine** [comment]
yeah, I installed simplekml  before use ulog2kml , but have no kml file output.  My device is mac .

**Comment by sampathkumarch** [comment]
How convert ulg 2 Excel 4 csv

**Comment by sampathkumarch** [comment]
How to convert ulg to kml please tell me step by step process

**Comment by bkueng** [comment]
For kml, see here: https://github.com/PX4/pyulog#convert-ulog-to-kml-files-ulog2kml, csv is also documented there.

**Comment by sampathkumarch** [comment]
but i have got errors how to resolve them
 ERROR: Could not find a version that satisfies the requirement pylog (from
versions: none)
ERROR: No matching distribution found for pylog

**Comment by bkueng** [comment]
Please provide the exact commands and ouput you get

**Comment by sampathkumarch** [comment]
ok  but now i am getting another error          :python: can't o  pen file
'install': [Errno 2] No such file or directory

 please tell me commands which commands i dont about this knowledge thats
why am asking please tell me ans

**Comment by sampathkumarch** [comment]
Okk I got  it final output . thanks for given a reply
