### ISSUE TITLE
pyulog not extractting vehicle_air_data

### ISSUE THREAD

**Issue by ambikaverma** [PX4/pyulog#30]
Hi

I trying to convert ulog data I have to csv using pyulog.
In a few u log files, if I use flight review tool, I can see the barometric data being plotted. Here is the link to the logs - https://logs.px4.io/plot_app?log=b852b2d8-93e1-4ae2-b204-6ffa89453f86
https://drive.google.com/file/d/19dI-8yOWR5siHObcn2UmUTob-soISPu5/view?usp=sharing

But when I try to convert it to csv using pyulog I dont see a file associated with vehicle_air_data. 
For some other files it works fine.

Not sure what the issue might be since flight review is able to plot it.
Any suggestions?
Thanks!

**Comment by bkueng** [comment]
Hi
The log is from an older version of the Firmware and the baro data is in the `sensor_combined` topic.
