### ISSUE TITLE
Shift GPS data to make log location anonymous 

### ISSUE THREAD

**Issue by ryanjAA** [PX4/pyulog#33]
There are quite a lot of scenarios where log data needs to be made somewhat anonymous prior to being able to being shared. After some conversations with @dagar, this can be a bit more tricky than initially thought since everything from gps, global position, home position, mission items, setpoints to even mag declination give a pretty clear indication of the location of the flight. There are just cases where substantial amounts of flight data can be used for analysis but often reporting where those flight took place isn't allowable, for whatever reason. 

Initial thoughts would be to create the ability to have a random offset of all location data and then hold that offset for all coordinates in the log, that way everything is related and will still follow course. for analysis. This is obviously very preliminary but here to get the conversation started.

**Comment by LorenzMeier** [comment]
@bkueng and I looked at that today as well. We definitely would like to enable that.

**Comment by ryanjAA** [comment]
That would be good. We were given BVLOS clearance last week but the location is not something we can report openly so cases like that make this something that is a newly present issue. We want to be able to share test flights but first things first.

**Comment by LorenzMeier** [comment]
Closing as stale.

**Comment by junwoo091400** [comment]
Hi! Just as a heads up, I have built this functionality, and can be found here:

https://github.com/junwoo091400/Anonymize_ULog_Data

**Comment by ryanjAA** [comment]
Awesome!! Thanks so much!
