### ISSUE TITLE
log the IMU and PWM outputs with timestamp in pixhawk 4 mini

### ISSUE THREAD

**Issue by ghost** [PX4/pyulog#65]
Hi I am research student ,
actually to find the inertial tensor I need IMU gyro and PWM outputs values with timestamp for this how can I boost the logging data to 400HZ. The log which is generated in QGC is limited to 50HZ but I need these values at which rate the pix hawk generates the signal. so can anyone help to log the IMU gyro and PWM outputs at its maximum rate . so that it is easy for me to find the inertial tensor

**Comment by bkueng** [comment]
Dup https://github.com/PX4/PX4-user_guide/issues/1702
