### ISSUE TITLE
Using Python script instead of command line to parse ulog files

### ISSUE THREAD

**Issue by emmaemmstein** [PX4/pyulog#71]
I want to be able to parse .ulg files using python script instead of a command line, how do I go about that? I'm used to using python script instead of command prompt in developing and running my code. I have tried a number of things but not getting it, please let me know what to do.

**Comment by bkueng** [comment]
If you have pyulog installed, you can just use it as any other python package - `from pyulog import ULog` ...

**Comment by emmaemmstein** [comment]
Thank you @bkueng I finally got it.
