### ISSUE TITLE
Description/Units of the various outputs

### ISSUE THREAD

**Issue by bradthelad1** [PX4/pyulog#72]
I noticed that several of the output csv's from pyulog do not contain units for the different outputted values, which has made some of these files somewhat difficult to use. 
My main concern is with the altitude contained in the vehicle_global_position csv, where 3 altitudes are given: alt, alt_ellipsoid, and terrain_alt. 
-Does PX4 use WGS84 for its ellipsoid? Is that the ellipsoid being referenced? 
-Is alt referring to MSL? 
-Where does the terrain_alt come from? 
-Are these parameters each in units of meters or feet?
Thanks in advance!

**Comment by dagar** [comment]
This all comes from the vehicle_global_position.msg in PX4.

https://github.com/PX4/PX4-Autopilot/blob/9b3cb6c75896a04dcd84647df597774752edd89a/msg/vehicle_global_position.msg#L11-L14

If you have any further questions or issues please continue from https://github.com/PX4/PX4-Autopilot. There are likely some fields that still need units and better documentation.
